### ISSUE TITLE
'&' Ampersand Character Splits into Multiple Values

### ISSUE THREAD

**Issue by nbdb** [microsoft/vsts-extension-multivalue-control#111]
When I originally select an option that contains an '&' it looks ok:

![Capture1](https://user-images.githubusercontent.com/45641624/60593594-19217880-9d71-11e9-9ae1-f7fdf43feb1e.PNG)

But upon selecting save, it breaks at the '&':
![Capture2](https://user-images.githubusercontent.com/45641624/60593650-39e9ce00-9d71-11e9-8f73-a156bcccad54.PNG)

We'd prefer to be able to keep the name as stored in our CRM software to help our internal reporting and billing. Thanks!

**Comment by AminTi** [comment]
Hi!,  please let me know if you till having the same issue

**Comment by nbdb** [comment]
This is corrected! It does look like the search is now case-sensitive though. I’d personally prefer if it wasn’t – I could open a new request for this if you’d like.

Thanks!

**Comment by babicahmed** [comment]
Still, the same issue persists when the backfield used is 'Text (multi-line field)'. When the backfield is 'Text (single line)' it works fine.

So, the ampersand '&' character splits into multiple values when the backfield is a multi-line field. We need to use this field type as a single line exceeds the number of characters that can be used, so when using 'Select All', it does not work.
