### ISSUE TITLE
Extremely long delay to display the control

### ISSUE THREAD

**Issue by JoseFMP** [Microsoft/vsts-extension-multivalue-control#39]
The control is working. I have a reasonable amount of options, i.e. around 5 options in the control, not a million.

When I open a PBI using this control, everything displays good as usual. However, this multivalue control takes a weirdly long amount of time to display... i.e. 20 seconds.

This really ruinds the UX of this control.

This happens most of the time, i.e. 90% of the time I open a PBI. Weird enough, around 10% of the PBIs I open, have this control inmediately available. I did not find any consistent pattern on which PBIs have it available and which takes weirdly long to load.

Any ideas?

**Comment by jdshkolnik** [comment]
We're seeing this behavior as well.

**Comment by mmanela** [comment]
@mohitbagra  @ostreifel  Can you take a look?

**Comment by mmanela** [comment]
@jdshkolnik  @Jose-CF  Are you still seeing this issue? Has the behavior changed?

**Comment by jdshkolnik** [comment]
Still happens in TFS.

**Comment by mmanela** [comment]
Can you take a fiddler trace of the page when this happens and share with us? We can provide a private email to send it to. @jdshkolnik

**Comment by jawn** [comment]
Same today in TFS 2017 Update 1 on a page with 3 multivalue controls. Sometimes slow, sometimes showing a message that it took too long

**Comment by mmanela** [comment]
What version of the control are you on?

**Comment by jawn** [comment]
@mmanela Can you say whether the likely bottleneck for this is
- our environment (TFS application server, SQL Server)
- calls between TFS server and Microsoft services.
- something else?

**Comment by Jose-CF** [comment]
Hello,

We are using VSTS.
Over here seems the issue is fixed. i.e. the box with the options appears now quickly all the time (seems).

**Comment by mmanela** [comment]
@jawn  There is a newer version of the multivalue control that you should update to.

**Comment by jawn** [comment]
Updated to 1.0.18.

Still see a slight delay from < 1 second to around a second, is this to be expected in a LAN environment between PC and TFS server? So should you ever see the 'loading' or should this be instantaneous?
![image](https://user-images.githubusercontent.com/1705112/37759413-d65f4cf8-2db3-11e8-8bd8-fa9c3486860e.png)

Note that we have 3 of these on 1 form.

**Comment by mmanela** [comment]
A slight delay is expected but the one you saw before wasn't. These extensions are sandboxed and loaded in frame after the form loads so they will not appear instantly. Ideally, once the JS is cached though, they should load quickly.

**Comment by ostreifel** [comment]
Closing this due to inactivity.
